### ISSUE TITLE
credentials.json downloaded as client_id.json

### ISSUE THREAD

**Issue by Twoody** [gsuitedevs/python-samples#53] opened 2018-12-01 20:24 UTC
## Expected Behavior
The code expects `credentials.json` to be downloaded.

## Actual Behavior
 What is downloaded is `client_id.json`.

## Steps to Reproduce the Problem

1. Follow all step to start a new project
2. Enable google calendar API for project
3. Receive a client_id.json file vs. the expected credentials.json file

## Specifications

- Python version (`python --version`)
- OS (Mac/Linux/Windows)

**Comment by grant** [comment] 2018-12-20 19:15
Thanks for the issue.
There are many ways to create credentials. The instructions specifically ask you to move the credentials file into the same directory as the code and rename the file if needed. I have just tried the quickstart with success.

See https://developers.google.com/calendar/quickstart/python

Closing due to unreproducability and lack of specifications. If you think this is an error, feel free to re-open the issue.

**Closed by grant** 2018-12-20 19:15 UTC
