### ISSUE TITLE
400 Bad Request - Gmail API

### ISSUE THREAD

**Issue by Barathwaja** [gsuitedevs/python-samples#119] opened 2019-07-17 11:13 UTC
Getting 400 Bad Request Error while accessing Gmail API using Python. Attached the error screenshot below.

![image](https://user-images.githubusercontent.com/5066436/61371189-d489f700-a8b1-11e9-9743-7cdffc30dea1.png)

**Comment by sqrrrl** [comment] 2019-07-17 17:03
This issue doesn't have sufficient information to be actionable. Was this from running one of the samples here? Or from your own code? Tried the quickstart, unable to reproduce this error.

Please provide steps to reproduce.

**Comment by Barathwaja** [comment] 2019-07-19 08:10
Attached the screenshot of the code below:


![image](https://user-images.githubusercontent.com/5066436/61519838-851b0680-aa2a-11e9-93e1-942790a59cc1.png)


**Note: I've removed service-account.json file purposely.**

**Comment by sqrrrl** [comment] 2019-07-19 15:28
Thanks. Since this isn't one of the samples, it's unfortunately out of scope for this issue tracker. For general help with the gmail API see https://developers.google.com/gmail/api/support

My hunch is that the issue is the use of service accounts itself. Service accounts act as their own users and I don't think have gmail enabled for them. The error message could definitely be improved and I'll file a bug against the API, but still, it's not expected to work. The only allowed use of service accounts with the gmail API is in domain management cases where the service account is used to impersonate users on behalf of an admin.

**Closed by sqrrrl** 2019-07-19 15:28 UTC

**Comment by Barathwaja** [comment] 2019-07-22 07:51
@sqrrrl Hey Steve, ok alright !! I also didn't got much info about using GMAIL API via Service Account but only the person who has the Overall Admin Console has the way to do it I guess.
